[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP"]

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
# Add pythonpath back
pythonpath = [
    ".", "src"
]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
# Explicitly set asyncio mode
asyncio_mode = "auto"

# asyncio_default_fixture_loop_scope = "session" # Example if you needed session scope later 